config/routes.rb
Rails.application.routes.draw do
  resources :movies do
    resources :ratings, only: [:create, :destroy]
  end
  resources :movies
  resources :categories
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "movies#index"
  root "movies#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
    # can :read, :all
    
    return unless user.present?
    
    if user.role == "admin"
      can :manage, :all
      can :create, :all
      can :destroy, :all
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :movies, dependent: :destroy
end

app/models/movie.rb
class Movie < ApplicationRecord
  
  has_rich_text    :description
  has_one_attached :preview_img
  belongs_to       :user
  belongs_to       :category
  has_many         :ratings, dependent: :destroy




  validates :title, presence: true, length: { maximum: 80 }
  validates :description, presence: true, length: { minimum: 20 }
  validates :preview_img, attached: true, content_type: %i[png jpg jpeg]
  validates :category_id, presence: true

  def average_rating
    ratings.average(:star).to_f.round(1)
  end

  def image_resize
    preview_img.variant(resize_to_limit: [800, 600]).processed
  end
end

app/models/rating.rb
class Rating < ApplicationRecord
  MAX_RATING = 10
  belongs_to :movie
  belongs_to :user
  accepts_nested_attributes_for :movie


  validates :star, numericality: {in: 0..MAX_RATING}

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  has_many :movies
  has_many :ratings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index]

  # GET /movies or /movies.json
  def index
    if params.has_key?(:category)
      @category = Category.find_by_name(params[:category])
      @movies = Movie.includes(:ratings).where(category: @category)
    else
      @movies = Movie.includes(:ratings)
    end
  end

  # GET /movies/1 or /movies/1.jsons
  def show

  end

  # GET /movies/new
  def new
    @movie = current_user.movies.new
    authorize! :create, @movie
  end

  # GET /movies/1/edit
  def edit
    authorize! :edit, @movie
  end

  # POST /movies or /movies.json
  def create
    @movie = current_user.movies.new(movie_params)
    authorize! :create, @movie
    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
  
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_path(@movie), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
    end
  end
   
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    authorize! :destroy, @movie
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title, :description, :preview_img, :category_id)
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @ratings = Rating.all
  end  

  def create
    @rating = Rating.create!(rating_params.merge(user_id: current_user.id))
    redirect_to root_path
  end


  private

  def rating_params
    params.require(:rating).permit(:star, :movie_id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def movie_categories
    @categories = Category.all.order(:name)
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/rating_helper.rb
module RatingHelper
  def star_rating_class(movie, index)
    if index < movie.average_rating
      "fill: yellow; stroke: yellow"
    else
      "fill: transparent; stroke: gray"
    end
  end

      
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_flash_message.html.erb
<div class="container">
  <p class="notice" style="color: green"><%= notice %></p>
  <p class="alert" style="color: red"><%= alert %></p>
</div>

app/views/layouts/_footer.html.erb
<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">© <%= Date.today.year %> IMDb-CLONE. All rights reserved.</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="p-2 mb-3 border-bottom bg-info">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <%= link_to root_path do %>
          <%= image_tag("logo.png", width: '200px' ) %>
        <% end %>

        <form class="input-group col-12 col-lg-auto mb-3 me-lg-auto me-lg-3 w-50 justify-content-center mb-md-0" role="search">
          <button class="btn btn-light btn-warning bg-light dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false"><%= t('header.dropdown.category')%></button>
          <ul class="dropdown-menu">
          <% movie_categories.each do |cat| %>
              <li>
                <%= link_to cat.name, movies_path(category: cat.name), class: "dropdown-item" %>
              </li>
            <% end %>
          </ul>
          <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
        </form>

        <%- if user_signed_in? %>
        <div class="dropdown text-end">
        <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
          <img src="https://gitlab.com/uploads/-/system/user/avatar/12332270/avatar.png" alt="mdo" width="32" height="32" class="rounded-circle">
        </a>
          <ul class="dropdown-menu text-small">
            <li><%= link_to t('movies.buttons.new'), new_movie_path, class: "dropdown-item" %></li>
            <li><a class="dropdown-item" href="#">Settings</a></li>
            <li><%= link_to t('devise.account'), edit_user_registration_path, class: "dropdown-item"%></li>
            <li><hr class="dropdown-divider"></li>
            <li>
              <%= button_to t('devise.logout'), destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </li>
          </ul>
        </div>
      <% else%>
        <div class="text-end">
          <%= link_to new_user_session_path do %>
            <button type="button" class="btn bg-success text-dark me-2"><%= t('devise.sessions.new.sign_in') %></button>
          <% end %>
          <%= link_to new_user_registration_path do %>
            <button type="button" class="btn bg-warning"><%= t('devise.registrations.new.sign_up') %></button>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImdbClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.0.0-beta.88/dist/themes/light.css" />
    <script type="module" src="https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.0.0-beta.88/dist/shoelace.js"></script>
    
  </head>

  <body>
    <%= render 'layouts/header'%>
    <%= render 'layouts/flash_message'%>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :preview_image, style: "display: block" %>
    <%= form.file_field :preview_img %>
  </div>

  <div class="field">
    <%= form.label :description, style: "display: block" %>
    <%= form.rich_text_area :description %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.select :category_id, options_for_select(movie_categories.collect{ |cat| [cat.name, cat.id]}) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_index_movie.html.erb
<div class="col" id="<%= dom_id movie %>">
  <div class="card shadow-sm">
    <%- if movie.preview_img.present? %>
      <%= image_tag movie.preview_img %>
    <% else %>
      <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
    <% end %>


    <div class="card-body">
      <p class="card-text"><%= movie.title %></p>
      <div class="d-flex mb-3">
        <% Rating::MAX_RATING.times do |n| %>
          <%= button_to movie_ratings_path(:rating),
              method: :post,
              params: {rating: {movie_id: movie.id, star: (n + 1)}} do %>
          <%= inline_svg_tag("star.svg",
              style: "width: 20px; height: 20px; #{star_rating_class(movie, n)}") %>
          <% end%>
        <% end %>
      </div>
      
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <%= link_to movie do %>
          <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
          <% end %>
          <% if can? :manage, movie %>
            <%= link_to edit_movie_path(movie) do %>
            <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>">
  <div class="d-flex bd-highlight mb-3">
  <div class="me-auto p-2 fs-1 bd-highlight"><%= movie.title %></div>
  <div class="p-2 bd-highlight">IMDB-clone rating:
  </div>
  <div class="p-2 bd-highlight"><%= movie.average_rating =%></div>
  </div>
  <div class='text-center'>
    <%= image_tag movie.image_resize if movie.preview_img.present? %>
  </div>
  
  <p>
  <strong> Категорія:</strong>
    <%= link_to movie.category.name, movie.category %>
  </p>
  
  <p>   
    <%= movie.description %>
  </p>
</div>

app/views/movies/edit.html.erb
<div class="container">
  <h1>Editing movie</h1>

  <%= render "form", movie: @movie %>

  <br>

  <div>
    <%= link_to "Show this movie", @movie %> |
    <%= link_to "Back to movies", movies_path %>
  </div>
</div>

app/views/movies/index.html.erb
<main>

  <div class="album py-5 bg-light">
  
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3" id="movies">

        <% @movies.each do |movie| %>
          <%= render "index_movie", movie: movie %>
        <% end %>

      </div>
    </div>
  </div>
</main>

app/views/movies/new.html.erb
<div class="container">
  <h1>New movie</h1>

  <%= render "form", movie: @movie %>
  
  <br>
  
  <div>
    <%= link_to "Back to movies", movies_path %>
  </div>
</div>

app/views/movies/show.html.erb
<div class="container">
  
  <%= render @movie %>
  
  <div class='row'>
    <div class='col-6'>
      <%= link_to "Back to movies", movies_path %>
    </div>
    <div class='col-6 text-center'>
      <% if can? :manage, @movie %>
      <%= button_to "Destroy this movie", @movie, method: :delete, form_class: 'd-inline right-position b-success' %>
      <%= button_to "Edit this movie", edit_movie_path(@movie), form_class: 'd-inline right-position b-danger' %>
      <% end %>
    </div>
  </div>
</div>

app/views/ratings/_rating.html.erb
<turbo-frame id="rating">
  <% Rating::MAX_RATING.times do |n| %>
    <%= button_to movie_ratings_path(movie_id: movie.id, star: (n + 1)),
        method: :post do %>
    <%= inline_svg_tag("star.svg",
        style: "width: 20px; height: 20px; #{star_rating_class(movie, n)}") %>
    <% end%>
  <% end %>
</turbo-frame>

app/views/welcome/header_form.html.erb
<%= form_with(model: @movie) do |form| %>
        
  <div>
    <%= form.select :category_id, options_for_select(@categories.collect{ |cat| [cat.name, cat.id]}) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/welcome/index.html.erb
<main>

<% if current_user %> 
  <p>You are <%= current_user.role %>!</p>
  <div> Welcome <%= current_user.email %> </div> 
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
  <% else %>
  <%= button_to "Sign in", new_user_session_path %> 
  <% end %>
</main>

# <%= turbo_frame_tag "vote", src: movie_ratings_path %>

(movie_id: movie.id, star: (n + 1))

:rating =>(movie.id: movie_id, star: 7)


<%= button_to movie_ratings_path(:rating),
              method: :post,
              params: {rating: {movie_id: movie.id, star: (n + 1)}} do %>